---
title: "Find a Gene Project"
author: "Jack Reddan (PID: A59010543)"
output: github_document
---

```{r}
library(ape)

BITree <- read.tree(file = "gor-MAFFT-20-NJ_tree.tre")

plot(BITree, 
     edge.width = 1,
     label.offset = 0.02,
     no.margin = TRUE,
     underscore = FALSE,
     lab4ut = "axial",
     align.tip.label = TRUE,
     type = "u",
     cex = 0.8,
     rotate.tree = -40)
```
  
```{r}
library(bio3d)
library(pheatmap)
```
```{r}
aln <- read.fasta("gor-MAFFT_aln-20_short.faa")
seq_id <- seqidentity(aln)
pheatmap(seq_id)
```

```{r}
hits <- blast.pdb(read.fasta("chlorokybus_gor_seq.faa"))
blast_hits <- plot.blast(hits)
```

```{r}
pdb <- get.pdb(blast_hits$pdb.id, path="pdbs", split=TRUE, gzip=TRUE)
```

```{r}
pdbs <- pdbaln(pdb[1:3], fit = TRUE)
hits$hit.tbl[1:3,]
```
```{r}
ids <- basename.pdb(pdbs$id)
plot(pdbs, labels=ids)
```

```{r}
con_seq <- read.fasta(file = "capsicum_annuum_gor_seq.faa")
hits <- blast.pdb(con_seq)
blast_hits <- plot.blast(hits)
```

```{r}
pdb <- get.pdb(blast_hits$pdb.id, path="pdbs", split=TRUE, gzip=TRUE)
```

```{r}
pdbs <- pdbaln(pdb[1:3], fit = TRUE)
hits$hit.tbl[1:3,]
```

